### ISSUE TITLE
kx.htmlsimplifier uses kx.iterator with `this`

### ISSUE THREAD

**Issue by daanvanham** [konfirm/konflux#14]
The addon `kx.htmlsimplifier` uses `kx.iterator` with `this`, resulting in errors, since `this` is `undefined` there ([sourcecode](https://github.com/konfirm/konflux/blob/separation/src/addon/htmlsimplify.js#L114-L122)).

**Comment by rspieker** [comment]
thanks for both reporting and fixing the issue!
